language: node_js

services:
  - docker

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

script:
  - export PUSH_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo ""; fi)
  - echo "PUSH_BRANCH=$PUSH_BRANCH, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - yarn global add gulp
  - yarn global add docpad
  - docpad install eco
  - docpad update
  - docpad upgrade
  - docpad generate --env static
  - gulp build-docs

after_success:
  - echo "after_success"
  - if [ "$PUSH_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dina-semantic-ui-docs .;
    docker tag dina-semantic-ui-docs dina/dina-semantic-ui-docs;
    docker push dina/dina-semantic-ui-docs;
    fi
